language: node_js
node_js:
  - 0.12
before_install:
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.0.2
  - export PATH=$PATH:`pwd`/bin
  - cd -
before_script:
  - phantomjs --version
  - casperjs --version
install:
  - npm install
notifications:
  slack: tlksio:fNbJkMIvB9GZKDDjfjZqAzBb
